apiVersion: v1
items:
- apiVersion: kafka.strimzi.io/v1beta2
  kind: KafkaConnect
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"kafka.strimzi.io/v1beta2","kind":"KafkaConnect","metadata":{"annotations":{"strimzi.io/use-connector-resources":"true"},"name":"debezium-connect-cluster","namespace":"debezium-example"},"spec":{"bootstrapServers":"debezium-cluster-kafka-bootstrap:9092","build":{"output":{"image":"10.96.69.69/debezium-connect-mysql:latest","type":"docker"},"plugins":[{"artifacts":[{"type":"tgz","url":"https://repo1.maven.org/maven2/io/debezium/debezium-connector-mysql/2.7.0.Final/debezium-connector-mysql-2.7.0.Final-plugin.tar.gz"}],"name":"debezium-mysql-connector"}]},"config":{"config.providers":"secrets","config.providers.secrets.class":"io.strimzi.kafka.KubernetesSecretConfigProvider","config.storage.replication.factor":3,"config.storage.topic":"connect-cluster-configs","group.id":"connect-cluster","offset.storage.partitions":25,"offset.storage.replication.factor":3,"offset.storage.topic":"connect-cluster-offsets","status.storage.partitions":5,"status.storage.replication.factor":3,"status.storage.topic":"connect-cluster-status"},"replicas":1,"version":"3.7.1"}}
      strimzi.io/use-connector-resources: "true"
    creationTimestamp: "2024-09-05T08:16:21Z"
    generation: 2
    name: debezium-connect-cluster
    namespace: debezium-example
    resourceVersion: "47796"
    uid: f6a9883a-3ffc-421a-9621-29ec67b5f834
  spec:
    bootstrapServers: debezium-cluster-kafka-bootstrap:9092
    build:
      output:
        image: 10.96.69.69/debezium-connect-mysql:latest
        type: docker
      plugins:
      - artifacts:
        - type: tgz
          url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-mysql/2.7.0.Final/debezium-connector-mysql-2.7.0.Final-plugin.tar.gz
        name: debezium-mysql-connector
    config:
      config.providers: secrets
      config.providers.secrets.class: io.strimzi.kafka.KubernetesSecretConfigProvider
      config.storage.replication.factor: 3
      config.storage.topic: connect-cluster-configs
      group.id: connect-cluster
      offset.storage.partitions: 25
      offset.storage.replication.factor: 3
      offset.storage.topic: connect-cluster-offsets
      status.storage.partitions: 5
      status.storage.replication.factor: 3
      status.storage.topic: connect-cluster-status
    replicas: 3
    version: 3.7.1
  status:
    conditions:
    - lastTransitionTime: "2024-09-05T14:01:55.119595843Z"
      status: "True"
      type: Ready
    connectorPlugins:
    - class: io.debezium.connector.mysql.MySqlConnector
      type: source
      version: 2.7.0.Final
    - class: org.apache.kafka.connect.mirror.MirrorCheckpointConnector
      type: source
      version: 3.7.1
    - class: org.apache.kafka.connect.mirror.MirrorHeartbeatConnector
      type: source
      version: 3.7.1
    - class: org.apache.kafka.connect.mirror.MirrorSourceConnector
      type: source
      version: 3.7.1
    labelSelector: strimzi.io/cluster=debezium-connect-cluster,strimzi.io/name=debezium-connect-cluster-connect,strimzi.io/kind=KafkaConnect
    observedGeneration: 2
    replicas: 3
    url: http://debezium-connect-cluster-connect-api.debezium-example.svc:8083
kind: List
metadata:
  resourceVersion: ""
