apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: pod-listing-binding
  namespace: debezium-example
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-listing-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: debezium-example
